[package]
name = "node_modules_deleter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3.2"
termcolor = "1.1.2"
atty = "0.2.14"
